# Generated by Django 3.0.5 on 2020-04-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmodel',
            name='read',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='readtext',
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
